name: Build Hugo
description: Build a static website with Hugo using GitHub Actions

branding:
  icon: package
  color: orange

runs:
  using: docker
  image: "dokcer://ghcr.io/hugomods:exts-0.127.0"
  entrypoint: ./entrypoint.sh
