name: Build Hugo
description: Build a static website with Hugo using GitHub Actions

branding:
  icon: package
  color: orange

runs:
  using: docker
  image: "docker://ghcr.io/hugomods/hugo:exts-0.127.0"
  entrypoint: ./entrypoint.sh
