name: Deploy Hugo to Cloudflare Pages
description: Deploy static websites built with Hugo to Cloudflare Pages.

branding:
  icon: upload-cloud
  color: orange

inputs:
  api_token:
    description: Cloudflare API token
    required: true
  account_id:
    description: Cloudflare Account ID
    required: true
  project_name:
    description: Cloudflare Project Name
    required: true
  public_directory: 
    description: Public directory containing the ready-to-deploy static files
    default: "public"
    required: false

runs:
  using: composite
  steps:
    - name: Build website
      uses: webgtx/hugo-deploy-cloudflare/.github/actions/hugo

    - name: Publish to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ inputs.api_token }}
        accountId: ${{ inputs.account_id }}
        projectName: ${{ inputs.project_name }}
        directory: ${{ inputs.public_directory }}
